### PR TITLE
Feat/ssr-fetch-profile-data

### PR DESCRIPTION
**Pull request by DanielSzczucki**
changed route payload structure
added universal route payload fetch fn

### CODE REVIEW

**Review by NerdbordMentor — APPROVED** [review]
# Code Review Report

## Task Goal
Fetch profile details from API endpoint using Next.js server components, so profile data is fetched server side, not client side.

## Code Changes Review

### app/api/profiles/[id]/route.ts
The changes in this file seem to be in line with the task requirements. The GET function now accepts `params` as an argument instead of `id`, which is extracted from the `params` object. The response structure has been modified to return the profile data under the `data` key instead of `profile`.

### app/api/user/[id]/route.ts
This is a new file and it seems to be correctly set up to fetch user data from the server side. It uses the Next.js server components as required by the task. The GET function is similar to the one in `app/api/profiles/[id]/route.ts`, which is a good sign of consistency.

### app/api/user/route.ts
The change in this file is minor and only affects the response structure, changing the key from `profile` to `data`. This change is consistent with the changes in other files.

### package.json
The TypeScript version has been updated. This change doesn't seem to be directly related to the task requirements, but it shouldn't cause any issues unless there are breaking changes in the new TypeScript version that affect other parts of the project.

### src/lib/GetRoutePayload.ts
This new file provides a function to fetch data from a given route. It seems to be set up correctly to fetch data from the server side, which is in line with the task requirements. However, there's a typo in the 'Content-Type' header value ('aplication/json' should be 'application/json').

### tsconfig.json
The changes in this file are purely formatting and don't affect how the code works.

## Summary
Overall, the code changes seem to cover the task requirements. The profile and user data are fetched from the server side using Next.js server components. The response structure has been modified consistently across different files. There's a minor issue with a typo in the 'Content-Type' header value in `src/lib/GetRoutePayload.ts`.

**Review by Sumick — CHANGES_REQUESTED** [review]
I don't see that server components are fetching profile data anywhere + we need to setup this `api` methods better. Now it's gonna be very hard to maintain, as `data` is union type of 4 different types. It won't be possible to properly use fetched data on the front end

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
Based on the task requirements and the provided code changes, here is the code review:

1. **app/api/profiles/[id]/route.ts**: The changes in this file seem to align with the task requirements. The profile details are fetched from the API endpoint using Next.js server components. The response structure has been modified slightly, but it should not affect the functionality as long as the client-side code is updated accordingly.

2. **app/api/user/[id]/route.ts**: This file has been added and it fetches user details from the API endpoint. However, this does not align with the task requirements which specifically mention fetching profile details, not user details.

3. **app/api/user/route.ts**: The changes in this file are similar to the first file. The response structure has been modified slightly, but it should not affect the functionality as long as the client-side code is updated accordingly.

4. **package.json**: The TypeScript version has been updated. This is not directly related to the task requirements but should not cause any issues unless there are breaking changes in the new version that affect other parts of the codebase.

5. **src/backend/user/user.service.ts** and **src/backend/user/user.types.ts**: The 'id' field has been removed from the user creation process. This is not directly related to the task requirements and could potentially cause issues if the 'id' field is required elsewhere in the codebase.

6. **src/lib/auth.ts**: The authentication process has been modified significantly. While this is not directly related to the task requirements, it's important to ensure that these changes do not introduce any security vulnerabilities or other issues.

7. **src/lib/client/apiClient.ts**: This file has been added and it fetches profile details from the API endpoint. This aligns with the task requirements.

8. **tsconfig.json**: The 'include' array has been reformatted but no actual changes have been made. This is not related to the task requirements.

In conclusion, most of the changes align with the task requirements of fetching profile details from an API endpoint using Next.js server components. However, there are some changes that do not directly relate to the task requirements and could potentially cause issues, such as the removal of the 'id' field in the user creation process and significant modifications to the authentication process.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
Based on the provided task requirements and code changes, here is the code review:

1. **app/api/profiles/[id]/route.ts**: The code changes in this file seem to align with the task requirements. The GET function now accepts `params` as an argument instead of `id`, and the `id` is extracted from the `params`. This is a standard way to handle route parameters in Next.js. The response structure has also been updated to return the profile data under the `data` key instead of `profile`, but this doesn't affect the task requirements.

2. **app/api/user/[id]/route.ts**: This new file adds a GET route for fetching user data by ID. However, this doesn't seem to be required by the task. The task only mentions fetching profile data, not user data.

3. **app/api/user/route.ts**: The change in this file is similar to the one in `app/api/profiles/[id]/route.ts`. The response structure has been updated, but this doesn't affect the task requirements.

4. **package.json**: The TypeScript version has been updated. This doesn't directly relate to the task requirements, but it's generally a good idea to keep dependencies up-to-date.

5. **src/backend/user/user.service.ts** and **src/backend/user/user.types.ts**: The `id` field has been removed from the `CreateUserPayload` interface and the `createUser` function. This doesn't seem to relate to the task requirements.

6. **src/lib/auth.ts**: This file has been significantly refactored. The changes involve how user sessions are handled and how users are created if they don't exist yet. These changes don't seem to directly relate to the task requirements.

7. **src/lib/client/apiClient.ts**: This new file adds a function for fetching profile data from the API. However, this function seems to be designed for client-side fetching, not server-side fetching as required by the task. In a Next.js server component, data would be fetched directly in the component, not through a fetch API.

8. **tsconfig.json**: The changes in this file are purely formatting changes and don't affect the task requirements.

In conclusion, while some of the changes align with the task requirements, others do not. Most notably, the requirement to fetch profile data using Next.js server components doesn't seem to be fulfilled. The added `getProfilePayload` function in `src/lib/client/apiClient.ts` is designed for client-side fetching, not server-side fetching.

**Review by Sumick — APPROVED** [review]

**Review by AniaPiWo — APPROVED** [review]

**Review by wawrzonnn — APPROVED** [review]

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
# Code Review

## Task goal
Fetch profile details from API endpoint using Next.js server components, so profile data is fetched server side, not client side.

## Code Changes Review

### app/(profile)/my-profile/page.tsx
The changes in this file seem to be in line with the task requirements. The profile data is fetched server-side using the `getProfilePayload` function.

### app/api/profiles/[id]/route.ts
The changes in this file are correct. The `GET` function now correctly extracts the `id` from the `params` object. The response format has also been changed to match the new format used in the frontend.

### app/api/user/[id]/route.ts
This file was added and it seems to be correctly implemented. It fetches user data based on the provided `id`.

### app/api/user/route.ts
The changes in this file are correct. The response format has been changed to match the new format used in the frontend.

### package.json
The TypeScript version has been updated. This change is not related to the task requirements, but it should not cause any issues.

### src/backend/user/user.service.ts
The `id` field has been removed from the `createUser` function. This change is not related to the task requirements, but it should not cause any issues.

### src/backend/user/user.types.ts
The `id` field has been removed from the `CreateUserPayload` interface. This change is not related to the task requirements, but it should not cause any issues.

### src/lib/auth.ts
The changes in this file are significant and seem to be related to user authentication rather than fetching profile data. These changes are not directly related to the task requirements.

### src/lib/client/apiClient.ts
This file was added and it seems to be correctly implemented. It fetches profile data based on the provided `id`.

### tsconfig.json
The changes in this file are formatting changes and do not affect the functionality of the code. They are not related to the task requirements.

## Conclusion
Most of the changes are in line with the task requirements. The profile data is fetched server-side using Next.js server components. However, there are some changes that are not directly related to the task requirements, such as user authentication and TypeScript version update.

**Review by Sumick — APPROVED** [review]

**Review by AniaPiWo — APPROVED** [review]

**Pull request closed without merging**
