### PR TITLE
Landing: fix: profile card

### PR DESCRIPTION
**Pull request by meczajkowski**
- **ProfileCard now supports smaller screens with a minimum width of 280px.** 
_This should be ok for our current requirements, considering that we do not support resolutions under 320px._
###
- **Moderation panel now uses ProfileCard with additional buttons.** 
_I am open for suggestions where to put  StateStatus coomponent from ModerationProfileListItem_
###
- **The Talent section is now aligned with the landing container at its maximum width.** 
_I don't know how it should behave when the landing container width is less than the combined width of three profile cards plus spacings. For now, they have a fixed width and will wrap when there isn't enough space._

image
image
Zrzut ekranu 2024-01-23 005609

### CODE REVIEW

**Review by NerdbordMentor — APPROVED** [review]
## Code Review Report

### Task Requirements Review

The task requirements provided through the Figma link and images show a design that needs to be implemented. The changes should reflect updates to the UI components, particularly the `ProfileCard` and related components, to match the new design specifications.

#### src/components/Accordion/Accordion.module.scss
- The removal of color styles from `.wrapper` and `.accordionContent` does not seem to directly relate to the task requirements as provided. However, if the design changes in Figma indicate that these color styles are no longer needed, then this change is valid.

#### src/components/ProfileCard/ProfileCard.module.scss
- The addition of `.frameWrapper` with responsive width settings aligns with the task requirements for responsive design.
- The update to `.frame` padding and width ensures that the card adheres to the new design.
- The removal of commented-out code and unused styles in `.detailsWrapper`, `.detailsContent`, and `.moderationFrame` is a good cleanup practice.
- The addition of `.wordWrap` utility class is likely to ensure text within the profile card does not overflow, which is a good practice for responsive design.

#### src/components/ProfileCard/ProfileCard.tsx
- The introduction of `withStateStatus` prop allows for conditional rendering of state status, which seems to be a requirement based on the provided images.
- The restructuring of the component to include `StateStatus` within a `ProfileCard` reflects the design requirement to show moderation status within the profile card.
- The use of `styles.frameWrapper` ensures that the card has a responsive width.

#### src/components/ProfileList/ModerationProfileListItem.tsx
- The refactoring to use `ProfileCard` directly is a significant improvement, as it reuses existing components and reduces code duplication.
- The removal of direct rendering logic for profile details and technologies in favor of using `ProfileCard` is in line with DRY (Don't Repeat Yourself) principles.

#### src/components/ProfileList/ProfileList.module.scss
- The removal of styles related to `.moderationFrame`, `.detailsWrapper`, and `.detailsContent` is appropriate since these styles have been moved to the `ProfileCard.module.scss`.

#### src/components/renderers/TechnologiesRenderer.tsx
- The inline style addition of `whiteSpace: 'nowrap'` ensures that the "+ Others" text does not wrap, which likely aligns with the design requirements.

### Summary
The code changes seem to align well with the task requirements based on the Figma design link provided. The refactoring efforts reduce code duplication and improve component reusability. The changes made to CSS modules support responsive design and match the visual updates required.

However, without specific details on color changes or other potential design updates not visible in the images provided, it's difficult to assess whether all visual aspects are covered. Assuming the Figma design specifies these changes, it appears that the code changes effectively cover the task requirements.

**Review by mmcode9407 — CHANGES_REQUESTED** [review]
Looks good! I've just left some comments. 
1. I think we shuld remove the `div` from `/components/ProfileList/ProfileList.tsx` component which it sets grid layout for only one div.
image
It couses something like this:
image
And we lose full container width.
2. We can move the `StateStatus` to components, like `/components/StateStatus/StateStatus.tsx`

**Review by hansac91 — APPROVED** [review]

**Review by AniaPiWo — APPROVED** [review]

**Review by mmcode9407 — APPROVED** [review]
👍

**Review by wawrzonnn — APPROVED** [review]

**Review by Sumick — APPROVED** [review]
First PR that got 6 approves :D

**Pull request merged**
