### PR TITLE
Feat implement mobile hamburger menu

### PR DESCRIPTION
**Pull request by mr-fox93**

### CODE REVIEW

**Review by wawrzonnn — APPROVED** [review]

**Review by meczajkowski — CHANGES_REQUESTED** [review]

**Comment by mr-fox93** [comment]
Hamburger Menu in the mobile view shows the content depending on the user's status whether it exists. I created a new MobileGitHubstars component because GitHubstars itself is used elsewhere in the application.

image

**Review by mr-fox93 — COMMENTED** [review]
add 'go back' button above profile details because on heade we have menu btn now

image

**Review by meczajkowski — APPROVED** [review]
Looks good!

**Pull request merged**
