### PR TITLE
fix: remove header from moderation view in user profile

### PR DESCRIPTION
**Pull request by mr-fox93**
image

### CODE REVIEW

**Review by Sumick — CHANGES_REQUESTED** [review]
Im not sure if it will fix the problem as we probably can need these `children` in other place. We should remove that header from different component

**Review by mmcode9407 — CHANGES_REQUESTED** [review]
You have to replace the `Header` with  the `UserProfileHeader` in `/moderation/page`.
And obviously, you have to leave the `children` prop in `UserProfileMain`.
Don't forget about `withBackButton` prop in `UserProfileHeader` 👍

**Comment by mr-fox93** [comment]
I brought it back children in UserProfileMain.
Change Header to UserProfileHeader in page.tsx for ModerationView like said @mmcode9407

**Review by mmcode9407 — APPROVED** [review]
GJ ❤️

**Review by Sumick — APPROVED** [review]
Looks good! 🔥

**Pull request merged**
