### PR TITLE
feat: ui banner for non registered user

### PR DESCRIPTION
**Pull request by SzDabrowski**
Desktop:
Screenshot from 2024-02-25 17-10-23
Mobile:
image

### CODE REVIEW

**Review by wawrzonnn — APPROVED** [review]
GJ

**Review by mr-fox93 — APPROVED** [review]

**Review by meczajkowski — APPROVED** [review]
I think we can move VisitorBanner components to our general components dir. What do You think about It?

**Comment by SzDabrowski** [comment]
> I think we can move VisitorBanner components to our general components dir. What do You think about It?

Good idea

**Review by Sumick — APPROVED** [review]
Looks good! Small comment to implement before merging ✌️

**Pull request merged**
