### PR TITLE
Feat/api-route-auth

### PR DESCRIPTION
**Pull request by DanielSzczucki**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
Based on the task requirements and the provided code changes, here is my review:

1. **app/api/session/route.ts**: The authorization check has been commented out in this file. This does not align with the task requirement of ensuring that incoming requests are always authorized before accessing resources. The code changes do not cover the task requirements in this file.

2. **middleware.ts**: This file has been added and it includes an authorization middleware as required. It checks for a token and returns a 401 status if no token is found, which aligns with the task requirements. However, the user data is not attached to the incoming requests as required by the task.

3. **src/lib/auth.ts**: The changes in this file include adding a session callback and modifying the jwt callback. The session callback adds user data to the session, which partially fulfills the task requirement of attaching user data to incoming requests. However, this is not done in the middleware as specified in the task requirements.

4. **tsconfig.json**: The changes in this file include adding "middleware.ts" to the "include" array. This is necessary for the middleware to be recognized by TypeScript and does not directly relate to the task requirements.

In conclusion, while some steps towards fulfilling the task requirements have been made, the code changes do not fully cover the task requirements. Specifically, user data is not attached to incoming requests in the middleware and authorization checks have been removed from `app/api/session/route.ts`.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
Based on the task requirements and the provided code changes, here is the review:

1. **app/api/session/route.ts**: The code changes in this file do not meet the task requirements. The authorization check has been commented out, which means that the route is no longer protected. The user data is not attached to incoming requests in this file.

2. **middleware.ts**: This newly added file meets the task requirements. It contains an authorization middleware that checks if a token is present in the incoming request. If a token is not present, it returns a 401 status code, indicating that authentication has failed. However, it does not attach the authorized user data to incoming requests.

3. **src/lib/auth.ts**: The changes in this file partially meet the task requirements. The `session` callback has been added to the `authOptions` object, which attaches the user data to the session. However, this does not necessarily mean that the user data is attached to every incoming request.

4. **tsconfig.json**: The changes in this file are not directly related to the task requirements but are necessary for including the new middleware file in the TypeScript compilation process.

In conclusion, while some progress has been made towards meeting the task requirements, they have not been fully met. The authorization middleware has been created, but user data is not consistently attached to all incoming requests. Furthermore, the protection of routes has been removed in `app/api/session/route.ts`, which contradicts the task goal of ensuring that all API routes are protected.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
Based on the task requirements and the provided code changes, here is the review:

1. **app/api/session/route.ts**: The changes in this file don't seem to directly relate to the task requirements. The change is a modification of a console log statement, which doesn't contribute to the creation of an authorization middleware or attaching user data to incoming requests.

2. **middleware.ts**: This new file appears to implement an authorization middleware as required. It uses the `getToken` function from `next-auth/jwt` to get the token from the request, and returns a 401 response if no token is found, which is a correct way to handle unauthorized requests. However, it doesn't seem to attach the authorized user data to the incoming requests, which is one of the task requirements.

3. **src/lib/auth.ts**: The changes in this file seem to be related to the session handling and user creation, but not directly related to the task requirements. The `session` callback was added to the `authOptions`, which modifies the session data to include the user id from the token. However, this doesn't seem to attach the user data to all incoming requests.

4. **tsconfig.json**: The changes in this file include the new `middleware.ts` file in the TypeScript compilation context, which is correct.

In conclusion, while some progress has been made towards meeting the task requirements, they are not fully met by these code changes. Specifically, the requirement to attach authorized user data to incoming requests is not fulfilled.

**Review by NerdbordMentor — APPROVED** [review]
Based on the provided task requirements and code changes, here is the code review:

1. **app/api/profiles/[id]/route.ts**: The changes in this file meet the task requirements. The `authorizeUser` function is called before getting a profile by ID, ensuring that only logged-in users can access this route.

2. **app/api/profiles/route.ts**: The changes in this file also meet the task requirements. The `authorizeUser` function is called before creating a user profile, ensuring that only logged-in users can create a profile. The user ID is now correctly retrieved from the authorized user instead of a non-existing token.

3. **app/api/session/route.ts**: This file has been removed. As long as session handling is correctly implemented elsewhere, this should not be an issue.

4. **app/api/user/route.ts**: The changes in this file meet the task requirements. The `authorizeUser` function is called before getting users and creating a user, ensuring that only logged-in users can access these routes.

5. **src/backend/user/user.service.ts**: A comment has been removed in this file. This change does not affect the task requirements.

6. **src/lib/auth.ts**: The changes in this file meet the task requirements. The `authorizeUser` function has been implemented and is used to check if a user is logged in. This function is correctly used in the routes to protect them.

7. **tsconfig.json**: A new file, "middleware.ts", has been added to the "include" array. As long as this file exists and is relevant to the project, this change should not be an issue.

In conclusion, the code changes cover the task requirements of protecting specific API routes so that only logged-in users can access them.

**Review by wawrzonnn — APPROVED** [review]

**Review by AniaPiWo — APPROVED** [review]

**Pull request merged**
