### PR TITLE
Fix/removing background in subheadings

### PR DESCRIPTION
**Pull request by transcendence12**
- removing background in subheadings

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Review of Code Changes in `apps/platform-app/src/app/globals.scss`

#### Code Changes:
```diff
@@ -30,4 +30,8 @@ body {
 
 ul {
   list-style-type: none;
+};
+
+h2, h3, h4, h5, h6 {
+  background: none;
 }
```

### Feedback:

1. **Bug Identification:**
   - There is a syntax error in the `ul` block. The semicolon `;` after the closing curly brace `}` is incorrect and should be removed.

2. **Task Requirements Coverage:**
   - The task requirement was to look for bugs. The identified syntax error in the `ul` block is a bug that needs to be fixed.

### Suggested Improvement:

To fix the syntax error, the code should be updated as follows:

```scss
ul {
  list-style-type: none;
}

h2, h3, h4, h5, h6 {
  background: none;
}
```

This change removes the incorrect semicolon after the closing curly brace of the `ul` block, ensuring proper syntax.

### Conclusion:
The provided code changes have a bug related to incorrect syntax in the `ul` block. The suggested improvement addresses this issue. The task requirement to look for bugs has been met with the identification of this syntax error.

**Review by NerdbordMentor — APPROVED** [review]
## Code Review Report

### Task Requirements
- Review the code changes and provide feedback.
- If there are any bugs, highlight them.
- Review if the code changes cover task requirements.

### Code Changes Reviewed
Filename: **apps/platform-app/src/app/globals.scss**
Status: **modified**
```diff
@@ -31,3 +31,7 @@ body {
 ul {
   list-style-type: none;
 }
+
+h2, h3, h4, h5, h6 {
+  background: none;
+}
```

### Feedback

1. **Code Coverage of Task Requirements:**
   - The task requirement was to look for bugs in the provided code changes.
   - The code changes involve adding a CSS rule to remove the background from heading elements (`h2, h3, h4, h5, h6`).

2. **Bugs:**
   - There are no apparent bugs in the provided code changes. The syntax is correct and the CSS rule is properly defined.

3. **Suggestions for Improvement:**
   - While there are no bugs, it might be useful to ensure that this change does not conflict with other styles in the application. For example, if other parts of the application rely on specific background styles for these heading elements, this change might override those styles unintentionally.

### Conclusion
- The code changes meet the task requirements as there are no bugs present.
- The added CSS rule is syntactically correct and should work as intended to remove the background from the specified heading elements.

**Comment by Wiecek-K** [comment]
LGFM

**Review by Sumick — APPROVED** [review]
Looks good!

**Review by Wiecek-K — APPROVED** [review]

**Pull request merged**
