### PR TITLE
Task/refactor headers in app

### PR DESCRIPTION
**Pull request by Wiecek-K**
I merged all header components into one to which we pass in props which variant of buttons to display.

### CODE REVIEW

**Review by mr-fox93 — APPROVED** [review]
looks good to me, the search bar in the mobile view does not work, I enter the name and it does not find the profile. Other than that it works fine.

**Comment by mr-fox93** [comment]
> > looks good to me, the search bar in the mobile view does not work, I enter the name and it does not find the profile. Other than that it works fine.
> 
> Do you mean the search bar on the /profiles page? If yes - it's weird because it works correctly on my end. image


sorry, my fault, i think this search bar is for 'name' :D but its for search in select.

**Review by wawrzonnn — APPROVED** [review]
Great Job Więcek

**Review by Sumick — APPROVED** [review]
Good job 🤙

**Pull request merged**
